### PR TITLE
minor formatting changes in README

### PR DESCRIPTION
**Pull request by keflavich**
Check to make sure that I didn't mess up the `**` things - I'm not sure what those `**`'s meant.

### CODE REVIEW

**Comment by jluastro** [comment]
All the **'s were supposed to be formatting (bulleted lists)

**Comment by keflavich** [comment]
But some were single `*`'s and others were double `**`s.  Was there intended to be a difference?

**Comment by jluastro** [comment]
list vs. sub-list

**Comment by keflavich** [comment]
in that case, I think I got it right.

**Pull request closed without merging**
